### ISSUE TITLE
BP: Meta blogpost on how to setup `distill` blog with netlify

### ISSUE THREAD

**Issue by shamindras** [shamindras/ss_personal_distill_blog#2]
- [x] Add `netlify` + `distill` post per [here](https://github.com/shamindras/ss_personal_blog/blob/master/content/post/2017-12-31-getting-tuftesque-with-blogging.Rmd)
- [x] Add screenshots and detail the process. Write from a first person perspective and explain why
- [x] Add links to [original distill blog creation](https://rstudio.github.io/distill/blog.html) page 
- [x] Also mention that I used this and adding more details so that I can express in my own words and include more details on custom domains and netlify

**Comment by shamindras** [comment]
close per #3
