### ISSUE TITLE
ENH/BP: Add `Makefile` + meta blogpost

### ISSUE THREAD

**Issue by shamindras** [shamindras/ss_personal_distill_blog#27]
- [ ] Add `categories` for blogposts similar [to here](https://blogs.rstudio.com/tensorflow/gallery.html)
- [ ] Add `Gallery` post similar [to here](https://github.com/rstudio/tensorflow-blog/blob/master/gallery.Rmd). Make sure to update `_site.yml` with [this ref](https://github.com/rstudio/tensorflow-blog/blob/master/_site.yml#L12)
- [ ] Add `Makefile` per [here](https://github.com/shamindras/ss_personal_blog/blob/master/Makefile) and [Karl Broman's makefile](https://github.com/kbroman/blog/blob/source/Makefile)
- [ ] Update `Makefile` to generate [rweekly.org](https://rweekly.org/submit) submission script for the blogpost
- [ ] Add a default blog post template and header and add to the `Makefile`
- [ ] Add creative commons similar [to here](https://blogs.rstudio.com/tensorflow/contributing.html) and [also here](https://github.com/rstudio/distill/blob/806955bd98bcb2589df77ef99574b58984a6aa3a/docs/_site.yml#L6)
- [ ] Write a blogpost detailing the steps similar to what we did [here](https://www.shamindras.com/posts/2019-07-11-setting-up-a-distill-blog-with-netlify/)
- [ ] Add `subscribe` option [see here](https://rstudio.github.io/distill/blog.html#subscriptions) and [also here](https://github.com/rstudio/tensorflow-blog/blob/master/_subscribe.html)
- [ ] Update referencing on LaTeX theorems [per this issue](https://github.com/rstudio/distill/issues/101#issue-467451992) raised

**Comment by shamindras** [comment]
duplicate of #28
