### ISSUE TITLE
ENH/BP: Update blog for disqus, GA, Gallery + meta blogpost

### ISSUE THREAD

**Issue by shamindras** [shamindras/ss_personal_distill_blog#4]
- [x] Change "Shamindra's Blog" to be "Shamindra Shrotriya's Blog"
- [x] Fix Typo "Shamindra's Shrotriya's blog" to be "Shamindra Shrotriya's blogposts"
- [x] Delete the [backup image folder](https://github.com/shamindras/ss_personal_distill_blog/tree/master/_posts/2019-07-11-setting-up-a-distill-blog-with-netlify/images/old_backup) from the previous post
- [x] Add `disqus`
- [x] Add netlify badge
- [x] Add `Google Analytics`
- [x] Add [twitter cards](https://rstudio.github.io/distill/metadata.html#twitter-card) for sharing posts 
- [x] Add **RSS** setup

**Comment by shamindras** [comment]
closed per #26
